esphome:
  name: ${devicename}

esp32:
  board: esp32s2
  variant: esp32s2
  framework:
    type: esp-idf

# Turn on the web server
web_server:

# Turn on the prometheus /metrics endpoint
prometheus:

preferences:
  flash_write_interval: 10min

wifi:
  min_auth_mode: WPA3

logger:

packages:
  mqtt: !include  ../mqtt.yaml
