esphome:
  name: ${devicename}

esp32:
  board: lolin_s2_mini
  variant: esp32s2
  framework:
    type: arduino
    version: latest


preferences:
  flash_write_interval: 10min

wifi:
  min_auth_mode: WPA3

logger:

packages:
  mqtt: !include  ../mqtt.yaml
