substitutions:
  devicename: bedroom_air_filter
  human_devicename: Bedroom Air Filter
  ip: 10.9.1.217

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml

esphome:
  name: ${devicename}

esp8266:
  board: esp8285

logger:
