substitutions:
  devicename: bedroom_fan
  human_devicename: Bedroom Fan
  ip: 10.9.1.214

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml

esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

logger:
