substitutions:
  devicename: family_room_fairy_lights
  human_devicename: Family Room Fairy Lights
  ip: 10.9.1.218

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml

esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

logger:
