substitutions:
  devicename: oil_heater_monitor
  human_devicename: Oil Heater Monitor
  ip: 10.9.1.209

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml

esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

logger:
