substitutions:
  devicename: workshop_fan
  human_devicename: Workshop Fan
  ip: 10.9.1.206

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml

esphome:
  name: ${devicename}

esp8266:
  board: esp01_1m

logger:
