substitutions:
  devicename: bunnys-bathroom
  human_devicename: Bunny's Bathroom
  version: "25.2.21.2"
  device_description: ${devicename} made by Apollo Automation - version ${version}.
  ip: 10.9.1.245

packages:
  msr2: !include common/apollo-msr2.yaml
