substitutions:
  devicename: bunnys_bathroom_bluetooth_proxy
  human_devicename: Bunnys Bathroom Bluetooth Proxy
  ip: 10.9.1.235
  icon: "mdi:bluetooth-connect"

packages:
  wifi: !include common/wifi.yaml
  base: !include common/base.yaml
  esp32: !include common/device-classes/esp32-idf.yaml


bluetooth_proxy:
  active: true

