substitutions:
  devicename: kitchen-sensor
  human_devicename: Kitchen Sensor
  version: "25.2.21.2"
  device_description: ${devicename} made by Apollo Automation - version ${version}.
  ip: 10.9.1.210

packages:
  msr2: !include common/apollo-msr2.yaml
